### ISSUE TITLE
Prerequisites cleanup

### ISSUE THREAD

**Issue by KiwiHawk** [BobsMods/bobsmods#12]
Investigate prerequisites issues listed here: https://forums.factorio.com/viewtopic.php?f=51&t=80473

- Hide:
  - `combat-robot-dispenser-equipment`
  - Base game recipe `sulfuric-acid`
  - Base game recipe `sulfur`
  - `small-alien-artifact`
  - `gem-ore`
- Add science pack to techs where the pack is required by a prerequisite tech
- Check if techs exist before adding prerequisites
- Remove military science from radar and rocket silo
- Add use for `tungsten-gear-wheel`
  - Item is currently unused, unless titanium or nitinol gear wheel doesn't exist
  - Maybe add to rocket engine recipe?

**Comment by mecejide** [comment]
Related: the RCU tech depends on a tech (advanced electronics 3) that uses prod sci without using prod sci itself.

**Comment by KiwiHawk** [comment]
Technology `fluid-handling` is a weird case. It unlocks somewhat unrelated things: storage-tanks, pumps, and a lot of barrelling recipes.

Split into three separate technologies:
- `fluid-handling`
  - Unlocks storage tanks, pump, and valves
  - Remains at current position in the tech tree
- `fluid-barrel-processing`
  - Unlocks `empty-barrel`, as well as all regular fluid barrelling recipes
  - Prerequisites `water-bore-1`, `steel-processing`, and `automation-science-pack`
  - Sister technology to the currently existing `gas-canisters`
- `fluid-canister-processing`
  - Unlocks `empty-canister` as well as all the canister filling recipes
  - Prerequisites `plastics` and thus indirectly `fluid-processing`

Tech `fluid-handling` unlocks the recipe `fill-petroleum-gas-barrel` and `empty-petroleum-gas-barrel` which require a gas bottle (Bob's mods), rather than a barrel (vanilla). Move these to `gas-canisters`.

Switch tech `cliff-explosives` to have `fluid-barrel-processing` as a prerequisite rather than `fluid-handling`

**Comment by KiwiHawk** [comment]
Only thing remaining is to get a higher resolution image for canister tech.

**Comment by KiwiHawk** [comment]
> Only thing remaining is to get a higher resolution image for canister tech.

Credit to [MoreScience-BobAngelsExtension](https://github.com/LovelySanta/FactorioMod-MoreScience-BobAngelsExtension) for the canister tech icon.
