### ISSUE TITLE
Add mod prerequisite

### ISSUE THREAD

**Issue by KiwiHawk** [BobsMods/bobsmods#14]
Add bobores as a hard dependency for bobplates. Currently it's optional.

I also had someone suggest adding bobplates as a hard dependency for bobrevamp. Not sure about this. Need to check what revamp adds or change with/without MCI.

**Comment by bobingabout** [comment]
Bobplates used to be a hard dependency of bobrevamp, it was designed to function as such out of the gate.
People complained.
It took a fair bit of effort to go through everything and make it function without bobplates to allow it to be optional.

**Comment by KiwiHawk** [comment]
Okay, leaving Revamp for now. Have just changed MCI.
