### ISSUE TITLE
Option to remove long reach from "short" Inserters

### ISSUE THREAD

**Issue by KiwiHawk** [BobsMods/bobsmods#25]
Add a setting to disable Long inserters 1 research.

![image](https://user-images.githubusercontent.com/59639/165019246-86cd6ef2-0625-48fe-a766-6c6dbcd3153d.png)

If this is disabled, Long inserters 2 and More inserters 2 will also be disabled. Inserter length cannot be changed.

Long inserter has 2 tile reach.
![image](https://user-images.githubusercontent.com/59639/165019452-78b8122b-9b25-4292-a882-2ba8bb9e325a.png)

All other inserters have a 1 tile reach.
![image](https://user-images.githubusercontent.com/59639/165019429-4f0339c5-12ce-4bcb-8851-661b36aa17a6.png)

https://mods.factorio.com/mod/bobinserters/discussion/6177e800078a84fad876fdc6

**Comment by atburghardt** [comment]
This feature should add more inserters beginning from fast inserter upwards.
Each Tier should get a 
- long inserter
- long filter 
- long stack inserter
- long filter stack inserter

**Comment by KiwiHawk** [comment]
If you want all those options, you just wouldn't enable this option. The option will be in Bob's Adjustable Inserters mod. The mod just adds configuration options. Doesn't add any new entities. (That's Bob's Logistics)

**Comment by atburghardt** [comment]
I don't think, that this is a good idea.
If the setting is enabled. You get all the different Tiers of normal/filter/stack/stack-filter inserters. 
These inserters will have a range of 1.
Then there will be 1 fast inserter, with a range of 2. No filter/stack/stack-filter version.
Range 3 inserters will be gone. 

This doesn't seem to be the right way.
