### ISSUE TITLE
Sound changes in Bob Warfare

### ISSUE THREAD

**Issue by Bloodymight** [BobsMods/bobsmods#31]
Hi
I uploaded

remove the (Bloodymight) from filename

[bobwarfare_1.1.3(Bloodymight).zip](https://github.com/BobsMods/bobsmods/files/8791380/bobwarfare_1.1.3.Bloodymight.zip)

**Comment by KiwiHawk** [comment]
https://mods.factorio.com/mod/bobwarfare/discussion/6291f1f8b64b25ba95f7a8ec

**Comment by Bloodymight** [comment]
The plasma turret sound effects are sampled and heavily edited, so there is no issue.
Same with the sniper rifle sounds.

The other sound effects are from other mods which I threw in and used for myself (Gun_Turret, laser-beam, Rifle, Tank_Turret, turret_fire)
I'm not sure which mod it was though, but I'll look it up when I have the time

**Comment by Bloodymight** [comment]
Hi, I played(modified) with the mod a little bit more and added some other sounds while doing so, thouth you guys might be interested in.

[bobwarfare_1.1.5(Bloodymight).zip](https://github.com/BobsMods/bobsmods/files/9032177/bobwarfare_1.1.5.Bloodymight.zip)


bonus information:

selfmade and/or heavily edited sample soundeffects:
plasma-turret-01.ogg 
plasma-explosion-01.ogg
plasma-explosion-02.ogg
Sniper_Rifle1.ogg
Sniper_Rifle2.ogg
Sniper_Rifle3.ogg
Sniper_Rifle4.ogg
Sniper_Rifle5.ogg
sniper_turret_shot.ogg
laser-turret-beam-01.ogg
laser-turret-idle-01.ogg

All the other sound files are from other factorio mods. which I found a few years ago.
(example: "BetterSounds_0.0.2", "weaponSoundsRedone_1.3.0"... but couldn't find the mod for the rifle1.ogg, rifle2.ogg and rifle3.ogg sounds)


changes I did from my part:

Adjusted sniper rifle numbers, so people have to think about positioning and when not to use the rifle(increased damage and range, higher cooldown time, people have to stand to shoot)

Added new Entity in turrets.lua
	-copy pasted bob_laser_turret(inputs) and renamed into bob_plasma_turret(inputs) so I can use different explosion effects
		-dying_explosion = "medium-explosion",
		into
		-dying_explosion = "laser-turret-explosion",

laser turret mk 6 and mk 7 (both are scaled up to 1.5)
modified beams.lua, light glow, different colored laser, ruby creates fire on impact, diamond too but with additional fire damage
new sound effect for laser turret mk 6 and mk 7 

new sound effect for sniper turret

**Comment by atburghardt** [comment]
@KiwiHawk @Bloodymight added the sounds to bobsmod. I musst admit, that I can't really hear a difference... 
Can you check if the new sounds are actually used? Need to check the part, where you changed some rifles etc. Should this be part of the issue and be udpated?

**Comment by Bloodymight** [comment]
@atburghardt
The latest official bobswarfare version doesn't have my sounds added, I uploaded a version where I added the sounds which you can see in my OP. You can check for example the plasma turret there

**Comment by atburghardt** [comment]
https://github.com/atburghardt/bobsmods/commit/aea4e86397050fe03144315382f819615543c67f

I added them in this commit in my forked bobmod. If you download it, you can test and see if I did it right.
It's also linked above my last comment.

**Comment by atburghardt** [comment]
> [atburghardt@aea4e86](https://github.com/atburghardt/bobsmods/commit/aea4e86397050fe03144315382f819615543c67f)
> 
> I added them in this commit in my forked bobmod. If you download it, you can test and see if I did it right. It's also linked above my last comment.

@Bloodymight could check if I added your Sounds right?

**Comment by Bloodymight** [comment]
@atburghardt
Hi and sorry for the late reply

https://github.com/BobsMods/bobsmods/issues/31#issuecomment-1271428298

As far as I can see only the turret sounds are missing in the turret.lua, or are not used to be more precise
example the plasma turret:

`  bob_plasma_turret{
    name = "bob-plasma-turret-1",
    health = 1000,
    turret_base_has_direction = true,

    drain = "48kW",
    buffer_capacity = "2500kJ",
    input_flow_limit = "1200kW",
    energy_consumption = "2400kJ",

    type = "projectile",
    projectile = "bob-plasma-projectile",
    target_type = "position",
    clamp_position = true,
    damage_modifier = 12 * 1,
    cooldown = 200,
    range = 60,
    sound = {{ filename = "__bobwarfare__/sound/plasma-turret-01.ogg", volume = 0.7, max_sounds_per_type = 4 }},`

what I also did is I scaled it up with higher levels, so,

plasma turret mk2 looks like this
`    sound = {{ filename = "__bobwarfare__/sound/plasma-turret-01.ogg", volume = 0.75, max_sounds_per_type = 4 }},`

mk3
`    sound = {{ filename = "__bobwarfare__/sound/plasma-turret-01.ogg", volume = 0.8, max_sounds_per_type = 4 }},`

mk4     
`sound = {{ filename = "__bobwarfare__/sound/plasma-turret-01.ogg", volume = 0.9, max_sounds_per_type = 4 }},`

mk5 
`    sound = {{ filename = "__bobwarfare__/sound/plasma-turret-01.ogg", volume = 1, max_sounds_per_type = 4 }},`

But I personally find the volume at 1 to be very loud, so you guys might want to adjust it to your liking
