### ISSUE TITLE
Long handed inserter next upgrade

### ISSUE THREAD

**Issue by KiwiHawk** [BobsMods/bobsmods#41]
![image](https://user-images.githubusercontent.com/59639/175449219-d396a455-0a03-487f-937c-f19c965be128.png)

https://mods.factorio.com/mod/bobinserters/discussion/62a08f82d7d1af68008ae7f3

Apparently cause by playing with either:
- Random Factorio Things
- Factorio Plus Plus

Issue was caused by #8

**Comment by atburghardt** [comment]
Random Factorio Things and the oldest boblogistics and bobinserters Versions on Github still produce the error.
![image](https://user-images.githubusercontent.com/9379708/193516147-5e01a21d-3e50-470c-a102-c3fe1add3eb8.png)

**Comment by atburghardt** [comment]
Factorio Plus Plus flags boblibrary as incompatible. Can't find their sourcecode on github to inspect when they flaggt it.

**Comment by KiwiHawk** [comment]
> Random Factorio Things and the bob 1.1 still produce the error. Can't reproduce a working Version

It worked with RandomFactorioThings + bobinserters < 1.1.5 . You had boblogistics in there as well. It should now work with any combination.
