### ISSUE TITLE
Krastorio 2 Mining Compatibility

### ISSUE THREAD

**Issue by KiwiHawk** [BobsMods/bobsmods#42]
https://discord.com/channels/351216213327609858/497860215010754560/982760329907933225
> Hey i added bob's mining and I've found 2 issues one pumpjacks can't pump oil from K2 and the second are i can't convert from one type of mine to the other from K2 typically the one both types are made from. 

![image](https://user-images.githubusercontent.com/59639/175450415-bc69d245-e8d0-49f6-8108-b8758f07ebf6.png)

**Comment by fctrusr** [comment]
Another problem related to miners in a K2 environment is that i am unable to upgrade from electric-mining-drill to electric-mining-drill-2 or electric-large-area-mining-drill-2 or any other tier of bob's miners

Response: "Electric mining drill is in the way"
or Selection is not available in an upgrade planner

**Comment by fctrusr** [comment]
found the cause, the property "fast replaceable group" is different
the electric mining drill shows : "electric-mining-drill" while bobs entities have the value "mining-drill"
