### ISSUE TITLE
Can not load my old save ( Adjustable Inserters mod )

### ISSUE THREAD

**Issue by spiralpower** [BobsMods/bobsmods#49]
I got an error when I loaded save with the latest Bob ( 1.1.5 )
If only Adjustable Inserters mod was an older version, could load
![1](https://user-images.githubusercontent.com/47108911/181859906-8601dc8e-ee32-46bf-a3a0-c59588097526.png)

save
https://drive.google.com/file/d/1Aiz64MR71eBdI74eA_KXJ0nRehOzW4u3/view?usp=sharing

**Comment by KiwiHawk** [comment]
@oorzkws Are you able to look at this? Seem the issue still isn't fixed
