### ISSUE TITLE
Atomic artillery shell range modifier

### ISSUE THREAD

**Issue by KiwiHawk** [BobsMods/bobsmods#59]
https://mods.factorio.com/mod/bobwarfare/discussion/62e5f82e65281a2acdfb742d

> The Atomic Artillery Shell states that it has ''Range modifier: 300%'' but as far as I can tell it has the exact same range as any other shell

If the modifier doesn't do anything, maybe it should be removed.

**Comment by atburghardt** [comment]
I did some testing and can confirm, that the range modifier isn't working.
The shooting speed modifier right next to the range modifier is working fine.
