### ISSUE TITLE
Unable To Access UI

### ISSUE THREAD

**Issue by pixeldragon95** [BobsMods/bobsmods#63]
I am trying to use the adjustable inserters mod and I am unable to access the UI to do so. I don't have the UI that usually sits in the top left and when I use shift+E it doesn't pull anything up though I have to hit esc twice to et to the menu afterwards. I am still able to use the keybinds to cycle it a bit however the spatial representation helps out immensely. I am using Factorio Version 1.1.68 and Mod Version 1.1.5. Included is a save showing the missing UI element and showing the issue with shift+E
[Solo2.zip](https://github.com/BobsMods/bobsmods/files/9502054/Solo2.zip)

**Comment by KiwiHawk** [comment]
The only mod you have enabled is Bob's Library mod. You need to enable Bob's adjustable inserters mod.
![image](https://user-images.githubusercontent.com/59639/188801384-3dc631f6-db31-4665-9dbb-109684fae9cf.png)
