### ISSUE TITLE
Sciences are coming out vanilla colors

### ISSUE THREAD

**Issue by redXathena** [BobsMods/bobsmods#65]
Hello, I posted about this in the Discussion section of the mod page. The yellow science is coming out red, and red is coming out green. As soon as the science hits player inventory, a chest, or a lab, it changes to the proper color, but it comes out the wrong color and stays that way on the belt. Attached are a picture I took from my save when I first posted on the mod portal page, and the requested new save file with the same issue.
[bug example.zip](https://github.com/BobsMods/bobsmods/files/9554858/bug.example.zip)
![Bob science snafu](https://user-images.githubusercontent.com/89969217/189848710-134c1017-3536-4e3c-9ec8-3bf34d160252.png)

**Comment by KiwiHawk** [comment]
[Science pack glow](https://mods.factorio.com/mod/Science_pack_glow) mod is causing the issue. It's overwriting how the science packs look when on belts. I've requested on their discord that they add support for Bob's Tech mod's Science pack colours update setting.
https://discord.com/channels/226684448844939265/615672576005636106/1019189494274076713

**Comment by KiwiHawk** [comment]
Science pack glow mod has been updated. Issue is resolved.
