### ISSUE TITLE
Introduce dedicated Radar research

### ISSUE THREAD

**Issue by adoa** [BobsMods/bobsmods#72]
With Burner-Power phase, "Electricity" tech unlocks radar 1. It would make most sense to introduce a dedicated "Radar 1" tech to unlock radar 1. Currently "Radars" tech unlocks "Radar 2" and "Radars 2" unlocks "Radar 3" which makes no sense whatsoever.

Even without burner-power phase it could makes sense to either lock "Radar 1" behind that research or keep "Radars 2" as the first tech to improve radars.

![grafik](https://user-images.githubusercontent.com/1843557/194332114-4c16c730-2047-48b4-ad8f-d749082ed9d4.png)

**Comment by KiwiHawk** [comment]
- Increment number of existing radar techs
  - This make the entity and tech numbers match: radars-2 unlocks radar-2
- Rename tech `radars` to `radars-2`
- Add new tech `radars-1`
  - Make vanilla radar unlocked by `radars-1`
  - If Burner power phase is enabled (from Bob's Tech mod), make `radars-1` depend on tech `electricity`
