### ISSUE TITLE
8-directional plasma cannons

### ISSUE THREAD

**Issue by Qatavin** [BobsMods/bobsmods#77]
When working on my own expansion for Bob's mods, one of the things I added was a tweak to plasma cannons to make their placement 8-directional instead of 4-directional. I had always found it a little troublesome that they couldn't point directly out of a corner in a wall. I order to get full coverage of all possible approaches, you'd need to build two plasma cannons when one would be more than sufficient in terms of damage output. This is especially problematic if the energy usage/drain of plasma cannons is increased in order to balance them.

The necessary modifications are fairly simple. One need only assemble the 8 directions of the folded image, the mask, and the shadow. The only issue I encountered when doing this is that there are no folding animations for the extra directions. The easiest solution I could find was to simply have the turret always in the deployed position, removing the folding and unfolding entirely. Here's what that looks like. Normally, this "folded" image would be with the neck of the cannon lowered and the sight on top retracted. I can provide the remaining layers (hr and normal) if requested, since I have them on hand.

![laser-turret-folded](https://user-images.githubusercontent.com/108201496/196459102-e91aae3e-b661-4ec9-af26-d2e7196db125.png)

**Comment by KiwiHawk** [comment]
Looks interesting! Are you able to make a PR with all the relevant changes?

Thanks!

**Comment by Qatavin** [comment]
I'm pretty much new to github, but I should be able to figure out how to do that.
